### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by josh-gree** [odlgroup/odlpp#15]
Hi when I try to build I get the following error;

```
CMake Error at CMakeLists.txt:28 (add_dependencies):
  add_dependencies called with incorrect number of arguments


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by adler-j** [comment]
It seems the error is on our part, the readme is unclear. Your package structure should look like this:

```
odlpp
├── build         <--- build should be here
├── cmake
├── odl_cpp_utils
├── odlpp
├── python
└── test
```

You get this error since you put the build directory like this:

```
odlpp
├── cmake
├── odl_cpp_utils
├── odlpp
│   └── build     <--- wrong position
├── python
└── test
```

It is obviously not clear what we mean by `odlpp/build` in the readme. I'll get this fixed.

Note:
odlpp is currently not used in any of the public facing operators of ODL, so you should be able to make do without it for now, unless you have a specific use-case, in which case I'm interested.
